// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

#pragma once

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

// The following structs are used to implement the lowest level
// of the FFI, and thus useful to multiple uniffied crates.
// We ensure they are declared exactly once, with a header guard, UNIFFI_SHARED_H.
#ifdef UNIFFI_SHARED_H
    // We also try to prevent mixing versions of shared uniffi header structs.
    // If you add anything to the #else block, you must increment the version suffix in UNIFFI_SHARED_HEADER_V4
    #ifndef UNIFFI_SHARED_HEADER_V4
        #error Combining helper code from multiple versions of uniffi is not supported
    #endif // ndef UNIFFI_SHARED_HEADER_V4
#else
#define UNIFFI_SHARED_H
#define UNIFFI_SHARED_HEADER_V4
// ⚠️ Attention: If you change this #else block (ending in `#endif // def UNIFFI_SHARED_H`) you *must* ⚠️
// ⚠️ increment the version suffix in all instances of UNIFFI_SHARED_HEADER_V4 in this file.           ⚠️

typedef struct RustBuffer
{
    uint64_t capacity;
    uint64_t len;
    uint8_t *_Nullable data;
} RustBuffer;

typedef struct ForeignBytes
{
    int32_t len;
    const uint8_t *_Nullable data;
} ForeignBytes;

// Error definitions
typedef struct RustCallStatus {
    int8_t code;
    RustBuffer errorBuf;
} RustCallStatus;

// ⚠️ Attention: If you change this #else block (ending in `#endif // def UNIFFI_SHARED_H`) you *must* ⚠️
// ⚠️ increment the version suffix in all instances of UNIFFI_SHARED_HEADER_V4 in this file.           ⚠️
#endif // def UNIFFI_SHARED_H
#ifndef UNIFFI_FFIDEF_RUST_FUTURE_CONTINUATION_CALLBACK
#define UNIFFI_FFIDEF_RUST_FUTURE_CONTINUATION_CALLBACK
typedef void (*UniffiRustFutureContinuationCallback)(uint64_t, int8_t
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_DROPPED_CALLBACK
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_DROPPED_CALLBACK
typedef void (*UniffiForeignFutureDroppedCallback)(uint64_t
    );

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_FREE
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_FREE
typedef void (*UniffiCallbackInterfaceFree)(uint64_t
    );

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_CLONE
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_CLONE
typedef uint64_t (*UniffiCallbackInterfaceClone)(uint64_t
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_DROPPED_CALLBACK_STRUCT
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_DROPPED_CALLBACK_STRUCT
typedef struct UniffiForeignFutureDroppedCallbackStruct {
    uint64_t handle;
    UniffiForeignFutureDroppedCallback _Nonnull free;
} UniffiForeignFutureDroppedCallbackStruct;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_U8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_U8
typedef struct UniffiForeignFutureResultU8 {
    uint8_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultU8;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U8
typedef void (*UniffiForeignFutureCompleteU8)(uint64_t, UniffiForeignFutureResultU8
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_I8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_I8
typedef struct UniffiForeignFutureResultI8 {
    int8_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultI8;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I8
typedef void (*UniffiForeignFutureCompleteI8)(uint64_t, UniffiForeignFutureResultI8
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_U16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_U16
typedef struct UniffiForeignFutureResultU16 {
    uint16_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultU16;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U16
typedef void (*UniffiForeignFutureCompleteU16)(uint64_t, UniffiForeignFutureResultU16
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_I16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_I16
typedef struct UniffiForeignFutureResultI16 {
    int16_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultI16;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I16
typedef void (*UniffiForeignFutureCompleteI16)(uint64_t, UniffiForeignFutureResultI16
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_U32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_U32
typedef struct UniffiForeignFutureResultU32 {
    uint32_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultU32;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U32
typedef void (*UniffiForeignFutureCompleteU32)(uint64_t, UniffiForeignFutureResultU32
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_I32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_I32
typedef struct UniffiForeignFutureResultI32 {
    int32_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultI32;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I32
typedef void (*UniffiForeignFutureCompleteI32)(uint64_t, UniffiForeignFutureResultI32
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_U64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_U64
typedef struct UniffiForeignFutureResultU64 {
    uint64_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultU64;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U64
typedef void (*UniffiForeignFutureCompleteU64)(uint64_t, UniffiForeignFutureResultU64
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_I64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_I64
typedef struct UniffiForeignFutureResultI64 {
    int64_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultI64;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I64
typedef void (*UniffiForeignFutureCompleteI64)(uint64_t, UniffiForeignFutureResultI64
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_F32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_F32
typedef struct UniffiForeignFutureResultF32 {
    float returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultF32;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F32
typedef void (*UniffiForeignFutureCompleteF32)(uint64_t, UniffiForeignFutureResultF32
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_F64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_F64
typedef struct UniffiForeignFutureResultF64 {
    double returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultF64;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F64
typedef void (*UniffiForeignFutureCompleteF64)(uint64_t, UniffiForeignFutureResultF64
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_RUST_BUFFER
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_RUST_BUFFER
typedef struct UniffiForeignFutureResultRustBuffer {
    RustBuffer returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultRustBuffer;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_RUST_BUFFER
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_RUST_BUFFER
typedef void (*UniffiForeignFutureCompleteRustBuffer)(uint64_t, UniffiForeignFutureResultRustBuffer
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_VOID
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_VOID
typedef struct UniffiForeignFutureResultVoid {
    RustCallStatus callStatus;
} UniffiForeignFutureResultVoid;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_VOID
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_VOID
typedef void (*UniffiForeignFutureCompleteVoid)(uint64_t, UniffiForeignFutureResultVoid
    );

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_APP_RECONCILER_METHOD0
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_APP_RECONCILER_METHOD0
typedef void (*UniffiCallbackInterfaceAppReconcilerMethod0)(uint64_t, RustBuffer, void* _Nonnull, 
        RustCallStatus *_Nonnull uniffiCallStatus
    );

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_BIOMETRIC_PROVIDER_METHOD0
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_BIOMETRIC_PROVIDER_METHOD0
typedef void (*UniffiCallbackInterfaceBiometricProviderMethod0)(uint64_t, RustBuffer* _Nonnull, 
        RustCallStatus *_Nonnull uniffiCallStatus
    );

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_BIOMETRIC_PROVIDER_METHOD1
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_BIOMETRIC_PROVIDER_METHOD1
typedef void (*UniffiCallbackInterfaceBiometricProviderMethod1)(uint64_t, RustBuffer, int8_t* _Nonnull, 
        RustCallStatus *_Nonnull uniffiCallStatus
    );

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_FILE_PICKER_PROVIDER_METHOD0
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_FILE_PICKER_PROVIDER_METHOD0
typedef void (*UniffiCallbackInterfaceFilePickerProviderMethod0)(uint64_t, RustBuffer* _Nonnull, 
        RustCallStatus *_Nonnull uniffiCallStatus
    );

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_KEYCHAIN_PROVIDER_METHOD0
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_KEYCHAIN_PROVIDER_METHOD0
typedef void (*UniffiCallbackInterfaceKeychainProviderMethod0)(uint64_t, RustBuffer, RustBuffer, RustBuffer, void* _Nonnull, 
        RustCallStatus *_Nonnull uniffiCallStatus
    );

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_KEYCHAIN_PROVIDER_METHOD1
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_KEYCHAIN_PROVIDER_METHOD1
typedef void (*UniffiCallbackInterfaceKeychainProviderMethod1)(uint64_t, RustBuffer, RustBuffer, RustBuffer* _Nonnull, 
        RustCallStatus *_Nonnull uniffiCallStatus
    );

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_KEYCHAIN_PROVIDER_METHOD2
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_KEYCHAIN_PROVIDER_METHOD2
typedef void (*UniffiCallbackInterfaceKeychainProviderMethod2)(uint64_t, RustBuffer, RustBuffer, void* _Nonnull, 
        RustCallStatus *_Nonnull uniffiCallStatus
    );

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_EMBEDDING_PROVIDER_METHOD0
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_EMBEDDING_PROVIDER_METHOD0
typedef void (*UniffiCallbackInterfaceEmbeddingProviderMethod0)(uint64_t, RustBuffer, RustBuffer* _Nonnull, 
        RustCallStatus *_Nonnull uniffiCallStatus
    );

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_LOCAL_LLM_PROVIDER_METHOD0
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_LOCAL_LLM_PROVIDER_METHOD0
typedef void (*UniffiCallbackInterfaceLocalLlmProviderMethod0)(uint64_t, RustBuffer, void* _Nonnull, 
        RustCallStatus *_Nonnull uniffiCallStatus
    );

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_LOCAL_LLM_PROVIDER_METHOD1
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_LOCAL_LLM_PROVIDER_METHOD1
typedef void (*UniffiCallbackInterfaceLocalLlmProviderMethod1)(uint64_t, RustBuffer, RustBuffer, uint64_t, void* _Nonnull, 
        RustCallStatus *_Nonnull uniffiCallStatus
    );

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_LOCAL_LLM_PROVIDER_METHOD2
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_LOCAL_LLM_PROVIDER_METHOD2
typedef void (*UniffiCallbackInterfaceLocalLlmProviderMethod2)(uint64_t, RustBuffer, RustBuffer* _Nonnull, 
        RustCallStatus *_Nonnull uniffiCallStatus
    );

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_LOCAL_LLM_PROVIDER_METHOD3
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_LOCAL_LLM_PROVIDER_METHOD3
typedef void (*UniffiCallbackInterfaceLocalLlmProviderMethod3)(uint64_t, RustBuffer, uint64_t, void* _Nonnull, 
        RustCallStatus *_Nonnull uniffiCallStatus
    );

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_LOCAL_LLM_PROVIDER_METHOD4
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_LOCAL_LLM_PROVIDER_METHOD4
typedef void (*UniffiCallbackInterfaceLocalLlmProviderMethod4)(uint64_t, void* _Nonnull, 
        RustCallStatus *_Nonnull uniffiCallStatus
    );

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_LOCAL_LLM_PROVIDER_METHOD5
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_LOCAL_LLM_PROVIDER_METHOD5
typedef void (*UniffiCallbackInterfaceLocalLlmProviderMethod5)(uint64_t, RustBuffer* _Nonnull, 
        RustCallStatus *_Nonnull uniffiCallStatus
    );

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_LOCAL_LLM_PROVIDER_METHOD6
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_LOCAL_LLM_PROVIDER_METHOD6
typedef void (*UniffiCallbackInterfaceLocalLlmProviderMethod6)(uint64_t, RustBuffer* _Nonnull, 
        RustCallStatus *_Nonnull uniffiCallStatus
    );

#endif
#ifndef UNIFFI_FFIDEF_V_TABLE_CALLBACK_INTERFACE_APP_RECONCILER
#define UNIFFI_FFIDEF_V_TABLE_CALLBACK_INTERFACE_APP_RECONCILER
typedef struct UniffiVTableCallbackInterfaceAppReconciler {
    UniffiCallbackInterfaceFree _Nonnull uniffiFree;
    UniffiCallbackInterfaceClone _Nonnull uniffiClone;
    UniffiCallbackInterfaceAppReconcilerMethod0 _Nonnull reconcile;
} UniffiVTableCallbackInterfaceAppReconciler;

#endif
#ifndef UNIFFI_FFIDEF_V_TABLE_CALLBACK_INTERFACE_BIOMETRIC_PROVIDER
#define UNIFFI_FFIDEF_V_TABLE_CALLBACK_INTERFACE_BIOMETRIC_PROVIDER
typedef struct UniffiVTableCallbackInterfaceBiometricProvider {
    UniffiCallbackInterfaceFree _Nonnull uniffiFree;
    UniffiCallbackInterfaceClone _Nonnull uniffiClone;
    UniffiCallbackInterfaceBiometricProviderMethod0 _Nonnull biometricStatus;
    UniffiCallbackInterfaceBiometricProviderMethod1 _Nonnull authenticate;
} UniffiVTableCallbackInterfaceBiometricProvider;

#endif
#ifndef UNIFFI_FFIDEF_V_TABLE_CALLBACK_INTERFACE_FILE_PICKER_PROVIDER
#define UNIFFI_FFIDEF_V_TABLE_CALLBACK_INTERFACE_FILE_PICKER_PROVIDER
typedef struct UniffiVTableCallbackInterfaceFilePickerProvider {
    UniffiCallbackInterfaceFree _Nonnull uniffiFree;
    UniffiCallbackInterfaceClone _Nonnull uniffiClone;
    UniffiCallbackInterfaceFilePickerProviderMethod0 _Nonnull pickFile;
} UniffiVTableCallbackInterfaceFilePickerProvider;

#endif
#ifndef UNIFFI_FFIDEF_V_TABLE_CALLBACK_INTERFACE_KEYCHAIN_PROVIDER
#define UNIFFI_FFIDEF_V_TABLE_CALLBACK_INTERFACE_KEYCHAIN_PROVIDER
typedef struct UniffiVTableCallbackInterfaceKeychainProvider {
    UniffiCallbackInterfaceFree _Nonnull uniffiFree;
    UniffiCallbackInterfaceClone _Nonnull uniffiClone;
    UniffiCallbackInterfaceKeychainProviderMethod0 _Nonnull store;
    UniffiCallbackInterfaceKeychainProviderMethod1 _Nonnull load;
    UniffiCallbackInterfaceKeychainProviderMethod2 _Nonnull delete;
} UniffiVTableCallbackInterfaceKeychainProvider;

#endif
#ifndef UNIFFI_FFIDEF_V_TABLE_CALLBACK_INTERFACE_EMBEDDING_PROVIDER
#define UNIFFI_FFIDEF_V_TABLE_CALLBACK_INTERFACE_EMBEDDING_PROVIDER
typedef struct UniffiVTableCallbackInterfaceEmbeddingProvider {
    UniffiCallbackInterfaceFree _Nonnull uniffiFree;
    UniffiCallbackInterfaceClone _Nonnull uniffiClone;
    UniffiCallbackInterfaceEmbeddingProviderMethod0 _Nonnull embed;
} UniffiVTableCallbackInterfaceEmbeddingProvider;

#endif
#ifndef UNIFFI_FFIDEF_V_TABLE_CALLBACK_INTERFACE_LOCAL_LLM_PROVIDER
#define UNIFFI_FFIDEF_V_TABLE_CALLBACK_INTERFACE_LOCAL_LLM_PROVIDER
typedef struct UniffiVTableCallbackInterfaceLocalLlmProvider {
    UniffiCallbackInterfaceFree _Nonnull uniffiFree;
    UniffiCallbackInterfaceClone _Nonnull uniffiClone;
    UniffiCallbackInterfaceLocalLlmProviderMethod0 _Nonnull loadModel;
    UniffiCallbackInterfaceLocalLlmProviderMethod1 _Nonnull downloadModelFile;
    UniffiCallbackInterfaceLocalLlmProviderMethod2 _Nonnull platformHttpRequest;
    UniffiCallbackInterfaceLocalLlmProviderMethod3 _Nonnull generate;
    UniffiCallbackInterfaceLocalLlmProviderMethod4 _Nonnull unload;
    UniffiCallbackInterfaceLocalLlmProviderMethod5 _Nonnull loadedModelPath;
    UniffiCallbackInterfaceLocalLlmProviderMethod6 _Nonnull deviceCapability;
} UniffiVTableCallbackInterfaceLocalLlmProvider;

#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_MANGO_CORE_FN_CLONE_FFIAPP
#define UNIFFI_FFIDEF_UNIFFI_MANGO_CORE_FN_CLONE_FFIAPP
uint64_t uniffi_mango_core_fn_clone_ffiapp(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_MANGO_CORE_FN_FREE_FFIAPP
#define UNIFFI_FFIDEF_UNIFFI_MANGO_CORE_FN_FREE_FFIAPP
void uniffi_mango_core_fn_free_ffiapp(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_MANGO_CORE_FN_CONSTRUCTOR_FFIAPP_NEW
#define UNIFFI_FFIDEF_UNIFFI_MANGO_CORE_FN_CONSTRUCTOR_FFIAPP_NEW
uint64_t uniffi_mango_core_fn_constructor_ffiapp_new(RustBuffer data_dir, uint64_t keychain, uint64_t embedding_provider, RustBuffer embedding_status, uint64_t local_llm_provider, uint64_t biometric_provider, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_MANGO_CORE_FN_METHOD_FFIAPP_DISPATCH
#define UNIFFI_FFIDEF_UNIFFI_MANGO_CORE_FN_METHOD_FFIAPP_DISPATCH
void uniffi_mango_core_fn_method_ffiapp_dispatch(uint64_t ptr, RustBuffer action, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_MANGO_CORE_FN_METHOD_FFIAPP_EXPORT_CONVERSATION_MARKDOWN
#define UNIFFI_FFIDEF_UNIFFI_MANGO_CORE_FN_METHOD_FFIAPP_EXPORT_CONVERSATION_MARKDOWN
RustBuffer uniffi_mango_core_fn_method_ffiapp_export_conversation_markdown(uint64_t ptr, RustBuffer conversation_id, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_MANGO_CORE_FN_METHOD_FFIAPP_GET_DIRECTORY_BOOKMARK
#define UNIFFI_FFIDEF_UNIFFI_MANGO_CORE_FN_METHOD_FFIAPP_GET_DIRECTORY_BOOKMARK
RustBuffer uniffi_mango_core_fn_method_ffiapp_get_directory_bookmark(uint64_t ptr, RustBuffer source_id, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_MANGO_CORE_FN_METHOD_FFIAPP_GET_RAW_ATTESTATION_REPORT
#define UNIFFI_FFIDEF_UNIFFI_MANGO_CORE_FN_METHOD_FFIAPP_GET_RAW_ATTESTATION_REPORT
RustBuffer uniffi_mango_core_fn_method_ffiapp_get_raw_attestation_report(uint64_t ptr, RustBuffer backend_id, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_MANGO_CORE_FN_METHOD_FFIAPP_LIST_DIRECTORY_FINGERPRINTS
#define UNIFFI_FFIDEF_UNIFFI_MANGO_CORE_FN_METHOD_FFIAPP_LIST_DIRECTORY_FINGERPRINTS
RustBuffer uniffi_mango_core_fn_method_ffiapp_list_directory_fingerprints(uint64_t ptr, RustBuffer source_id, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_MANGO_CORE_FN_METHOD_FFIAPP_LISTEN_FOR_UPDATES
#define UNIFFI_FFIDEF_UNIFFI_MANGO_CORE_FN_METHOD_FFIAPP_LISTEN_FOR_UPDATES
void uniffi_mango_core_fn_method_ffiapp_listen_for_updates(uint64_t ptr, uint64_t reconciler, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_MANGO_CORE_FN_METHOD_FFIAPP_READ_ENCRYPTED_IMAGE
#define UNIFFI_FFIDEF_UNIFFI_MANGO_CORE_FN_METHOD_FFIAPP_READ_ENCRYPTED_IMAGE
RustBuffer uniffi_mango_core_fn_method_ffiapp_read_encrypted_image(uint64_t ptr, RustBuffer message_id, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_MANGO_CORE_FN_METHOD_FFIAPP_STATE
#define UNIFFI_FFIDEF_UNIFFI_MANGO_CORE_FN_METHOD_FFIAPP_STATE
RustBuffer uniffi_mango_core_fn_method_ffiapp_state(uint64_t ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_MANGO_CORE_FN_METHOD_FFIAPP_SYNC
#define UNIFFI_FFIDEF_UNIFFI_MANGO_CORE_FN_METHOD_FFIAPP_SYNC
void uniffi_mango_core_fn_method_ffiapp_sync(uint64_t ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_MANGO_CORE_FN_CLONE_LOCALGENERATIONCONTEXT
#define UNIFFI_FFIDEF_UNIFFI_MANGO_CORE_FN_CLONE_LOCALGENERATIONCONTEXT
uint64_t uniffi_mango_core_fn_clone_localgenerationcontext(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_MANGO_CORE_FN_FREE_LOCALGENERATIONCONTEXT
#define UNIFFI_FFIDEF_UNIFFI_MANGO_CORE_FN_FREE_LOCALGENERATIONCONTEXT
void uniffi_mango_core_fn_free_localgenerationcontext(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_MANGO_CORE_FN_METHOD_LOCALGENERATIONCONTEXT_EMIT_ERROR
#define UNIFFI_FFIDEF_UNIFFI_MANGO_CORE_FN_METHOD_LOCALGENERATIONCONTEXT_EMIT_ERROR
void uniffi_mango_core_fn_method_localgenerationcontext_emit_error(uint64_t ptr, RustBuffer message, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_MANGO_CORE_FN_METHOD_LOCALGENERATIONCONTEXT_EMIT_TOKEN
#define UNIFFI_FFIDEF_UNIFFI_MANGO_CORE_FN_METHOD_LOCALGENERATIONCONTEXT_EMIT_TOKEN
void uniffi_mango_core_fn_method_localgenerationcontext_emit_token(uint64_t ptr, RustBuffer token, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_MANGO_CORE_FN_METHOD_LOCALGENERATIONCONTEXT_IS_CANCELLED
#define UNIFFI_FFIDEF_UNIFFI_MANGO_CORE_FN_METHOD_LOCALGENERATIONCONTEXT_IS_CANCELLED
int8_t uniffi_mango_core_fn_method_localgenerationcontext_is_cancelled(uint64_t ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_MANGO_CORE_FN_CLONE_LOCALMODELDOWNLOADCONTEXT
#define UNIFFI_FFIDEF_UNIFFI_MANGO_CORE_FN_CLONE_LOCALMODELDOWNLOADCONTEXT
uint64_t uniffi_mango_core_fn_clone_localmodeldownloadcontext(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_MANGO_CORE_FN_FREE_LOCALMODELDOWNLOADCONTEXT
#define UNIFFI_FFIDEF_UNIFFI_MANGO_CORE_FN_FREE_LOCALMODELDOWNLOADCONTEXT
void uniffi_mango_core_fn_free_localmodeldownloadcontext(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_MANGO_CORE_FN_METHOD_LOCALMODELDOWNLOADCONTEXT_EMIT_PROGRESS
#define UNIFFI_FFIDEF_UNIFFI_MANGO_CORE_FN_METHOD_LOCALMODELDOWNLOADCONTEXT_EMIT_PROGRESS
void uniffi_mango_core_fn_method_localmodeldownloadcontext_emit_progress(uint64_t ptr, uint64_t downloaded_bytes, RustBuffer total_bytes, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_MANGO_CORE_FN_INIT_CALLBACK_VTABLE_APPRECONCILER
#define UNIFFI_FFIDEF_UNIFFI_MANGO_CORE_FN_INIT_CALLBACK_VTABLE_APPRECONCILER
void uniffi_mango_core_fn_init_callback_vtable_appreconciler(const UniffiVTableCallbackInterfaceAppReconciler* _Nonnull vtable
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_MANGO_CORE_FN_INIT_CALLBACK_VTABLE_BIOMETRICPROVIDER
#define UNIFFI_FFIDEF_UNIFFI_MANGO_CORE_FN_INIT_CALLBACK_VTABLE_BIOMETRICPROVIDER
void uniffi_mango_core_fn_init_callback_vtable_biometricprovider(const UniffiVTableCallbackInterfaceBiometricProvider* _Nonnull vtable
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_MANGO_CORE_FN_INIT_CALLBACK_VTABLE_FILEPICKERPROVIDER
#define UNIFFI_FFIDEF_UNIFFI_MANGO_CORE_FN_INIT_CALLBACK_VTABLE_FILEPICKERPROVIDER
void uniffi_mango_core_fn_init_callback_vtable_filepickerprovider(const UniffiVTableCallbackInterfaceFilePickerProvider* _Nonnull vtable
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_MANGO_CORE_FN_INIT_CALLBACK_VTABLE_KEYCHAINPROVIDER
#define UNIFFI_FFIDEF_UNIFFI_MANGO_CORE_FN_INIT_CALLBACK_VTABLE_KEYCHAINPROVIDER
void uniffi_mango_core_fn_init_callback_vtable_keychainprovider(const UniffiVTableCallbackInterfaceKeychainProvider* _Nonnull vtable
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_MANGO_CORE_FN_INIT_CALLBACK_VTABLE_EMBEDDINGPROVIDER
#define UNIFFI_FFIDEF_UNIFFI_MANGO_CORE_FN_INIT_CALLBACK_VTABLE_EMBEDDINGPROVIDER
void uniffi_mango_core_fn_init_callback_vtable_embeddingprovider(const UniffiVTableCallbackInterfaceEmbeddingProvider* _Nonnull vtable
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_MANGO_CORE_FN_INIT_CALLBACK_VTABLE_LOCALLLMPROVIDER
#define UNIFFI_FFIDEF_UNIFFI_MANGO_CORE_FN_INIT_CALLBACK_VTABLE_LOCALLLMPROVIDER
void uniffi_mango_core_fn_init_callback_vtable_localllmprovider(const UniffiVTableCallbackInterfaceLocalLlmProvider* _Nonnull vtable
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_MANGO_CORE_FN_FUNC_KNOWN_PROVIDER_PRESETS
#define UNIFFI_FFIDEF_UNIFFI_MANGO_CORE_FN_FUNC_KNOWN_PROVIDER_PRESETS
RustBuffer uniffi_mango_core_fn_func_known_provider_presets(RustCallStatus *_Nonnull out_status
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_MANGO_CORE_FN_FUNC_MODEL_SUPPORTS_VISION
#define UNIFFI_FFIDEF_UNIFFI_MANGO_CORE_FN_FUNC_MODEL_SUPPORTS_VISION
int8_t uniffi_mango_core_fn_func_model_supports_vision(RustBuffer model_id, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_MANGO_CORE_FN_FUNC_LOCAL_MODEL_CATALOG
#define UNIFFI_FFIDEF_UNIFFI_MANGO_CORE_FN_FUNC_LOCAL_MODEL_CATALOG
RustBuffer uniffi_mango_core_fn_func_local_model_catalog(RustCallStatus *_Nonnull out_status
    
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_MANGO_CORE_RUSTBUFFER_ALLOC
#define UNIFFI_FFIDEF_FFI_MANGO_CORE_RUSTBUFFER_ALLOC
RustBuffer ffi_mango_core_rustbuffer_alloc(uint64_t size, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_MANGO_CORE_RUSTBUFFER_FROM_BYTES
#define UNIFFI_FFIDEF_FFI_MANGO_CORE_RUSTBUFFER_FROM_BYTES
RustBuffer ffi_mango_core_rustbuffer_from_bytes(ForeignBytes bytes, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_MANGO_CORE_RUSTBUFFER_FREE
#define UNIFFI_FFIDEF_FFI_MANGO_CORE_RUSTBUFFER_FREE
void ffi_mango_core_rustbuffer_free(RustBuffer buf, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_MANGO_CORE_RUSTBUFFER_RESERVE
#define UNIFFI_FFIDEF_FFI_MANGO_CORE_RUSTBUFFER_RESERVE
RustBuffer ffi_mango_core_rustbuffer_reserve(RustBuffer buf, uint64_t additional, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_MANGO_CORE_RUST_FUTURE_POLL_U8
#define UNIFFI_FFIDEF_FFI_MANGO_CORE_RUST_FUTURE_POLL_U8
void ffi_mango_core_rust_future_poll_u8(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_MANGO_CORE_RUST_FUTURE_CANCEL_U8
#define UNIFFI_FFIDEF_FFI_MANGO_CORE_RUST_FUTURE_CANCEL_U8
void ffi_mango_core_rust_future_cancel_u8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_MANGO_CORE_RUST_FUTURE_FREE_U8
#define UNIFFI_FFIDEF_FFI_MANGO_CORE_RUST_FUTURE_FREE_U8
void ffi_mango_core_rust_future_free_u8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_MANGO_CORE_RUST_FUTURE_COMPLETE_U8
#define UNIFFI_FFIDEF_FFI_MANGO_CORE_RUST_FUTURE_COMPLETE_U8
uint8_t ffi_mango_core_rust_future_complete_u8(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_MANGO_CORE_RUST_FUTURE_POLL_I8
#define UNIFFI_FFIDEF_FFI_MANGO_CORE_RUST_FUTURE_POLL_I8
void ffi_mango_core_rust_future_poll_i8(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_MANGO_CORE_RUST_FUTURE_CANCEL_I8
#define UNIFFI_FFIDEF_FFI_MANGO_CORE_RUST_FUTURE_CANCEL_I8
void ffi_mango_core_rust_future_cancel_i8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_MANGO_CORE_RUST_FUTURE_FREE_I8
#define UNIFFI_FFIDEF_FFI_MANGO_CORE_RUST_FUTURE_FREE_I8
void ffi_mango_core_rust_future_free_i8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_MANGO_CORE_RUST_FUTURE_COMPLETE_I8
#define UNIFFI_FFIDEF_FFI_MANGO_CORE_RUST_FUTURE_COMPLETE_I8
int8_t ffi_mango_core_rust_future_complete_i8(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_MANGO_CORE_RUST_FUTURE_POLL_U16
#define UNIFFI_FFIDEF_FFI_MANGO_CORE_RUST_FUTURE_POLL_U16
void ffi_mango_core_rust_future_poll_u16(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_MANGO_CORE_RUST_FUTURE_CANCEL_U16
#define UNIFFI_FFIDEF_FFI_MANGO_CORE_RUST_FUTURE_CANCEL_U16
void ffi_mango_core_rust_future_cancel_u16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_MANGO_CORE_RUST_FUTURE_FREE_U16
#define UNIFFI_FFIDEF_FFI_MANGO_CORE_RUST_FUTURE_FREE_U16
void ffi_mango_core_rust_future_free_u16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_MANGO_CORE_RUST_FUTURE_COMPLETE_U16
#define UNIFFI_FFIDEF_FFI_MANGO_CORE_RUST_FUTURE_COMPLETE_U16
uint16_t ffi_mango_core_rust_future_complete_u16(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_MANGO_CORE_RUST_FUTURE_POLL_I16
#define UNIFFI_FFIDEF_FFI_MANGO_CORE_RUST_FUTURE_POLL_I16
void ffi_mango_core_rust_future_poll_i16(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_MANGO_CORE_RUST_FUTURE_CANCEL_I16
#define UNIFFI_FFIDEF_FFI_MANGO_CORE_RUST_FUTURE_CANCEL_I16
void ffi_mango_core_rust_future_cancel_i16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_MANGO_CORE_RUST_FUTURE_FREE_I16
#define UNIFFI_FFIDEF_FFI_MANGO_CORE_RUST_FUTURE_FREE_I16
void ffi_mango_core_rust_future_free_i16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_MANGO_CORE_RUST_FUTURE_COMPLETE_I16
#define UNIFFI_FFIDEF_FFI_MANGO_CORE_RUST_FUTURE_COMPLETE_I16
int16_t ffi_mango_core_rust_future_complete_i16(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_MANGO_CORE_RUST_FUTURE_POLL_U32
#define UNIFFI_FFIDEF_FFI_MANGO_CORE_RUST_FUTURE_POLL_U32
void ffi_mango_core_rust_future_poll_u32(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_MANGO_CORE_RUST_FUTURE_CANCEL_U32
#define UNIFFI_FFIDEF_FFI_MANGO_CORE_RUST_FUTURE_CANCEL_U32
void ffi_mango_core_rust_future_cancel_u32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_MANGO_CORE_RUST_FUTURE_FREE_U32
#define UNIFFI_FFIDEF_FFI_MANGO_CORE_RUST_FUTURE_FREE_U32
void ffi_mango_core_rust_future_free_u32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_MANGO_CORE_RUST_FUTURE_COMPLETE_U32
#define UNIFFI_FFIDEF_FFI_MANGO_CORE_RUST_FUTURE_COMPLETE_U32
uint32_t ffi_mango_core_rust_future_complete_u32(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_MANGO_CORE_RUST_FUTURE_POLL_I32
#define UNIFFI_FFIDEF_FFI_MANGO_CORE_RUST_FUTURE_POLL_I32
void ffi_mango_core_rust_future_poll_i32(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_MANGO_CORE_RUST_FUTURE_CANCEL_I32
#define UNIFFI_FFIDEF_FFI_MANGO_CORE_RUST_FUTURE_CANCEL_I32
void ffi_mango_core_rust_future_cancel_i32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_MANGO_CORE_RUST_FUTURE_FREE_I32
#define UNIFFI_FFIDEF_FFI_MANGO_CORE_RUST_FUTURE_FREE_I32
void ffi_mango_core_rust_future_free_i32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_MANGO_CORE_RUST_FUTURE_COMPLETE_I32
#define UNIFFI_FFIDEF_FFI_MANGO_CORE_RUST_FUTURE_COMPLETE_I32
int32_t ffi_mango_core_rust_future_complete_i32(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_MANGO_CORE_RUST_FUTURE_POLL_U64
#define UNIFFI_FFIDEF_FFI_MANGO_CORE_RUST_FUTURE_POLL_U64
void ffi_mango_core_rust_future_poll_u64(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_MANGO_CORE_RUST_FUTURE_CANCEL_U64
#define UNIFFI_FFIDEF_FFI_MANGO_CORE_RUST_FUTURE_CANCEL_U64
void ffi_mango_core_rust_future_cancel_u64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_MANGO_CORE_RUST_FUTURE_FREE_U64
#define UNIFFI_FFIDEF_FFI_MANGO_CORE_RUST_FUTURE_FREE_U64
void ffi_mango_core_rust_future_free_u64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_MANGO_CORE_RUST_FUTURE_COMPLETE_U64
#define UNIFFI_FFIDEF_FFI_MANGO_CORE_RUST_FUTURE_COMPLETE_U64
uint64_t ffi_mango_core_rust_future_complete_u64(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_MANGO_CORE_RUST_FUTURE_POLL_I64
#define UNIFFI_FFIDEF_FFI_MANGO_CORE_RUST_FUTURE_POLL_I64
void ffi_mango_core_rust_future_poll_i64(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_MANGO_CORE_RUST_FUTURE_CANCEL_I64
#define UNIFFI_FFIDEF_FFI_MANGO_CORE_RUST_FUTURE_CANCEL_I64
void ffi_mango_core_rust_future_cancel_i64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_MANGO_CORE_RUST_FUTURE_FREE_I64
#define UNIFFI_FFIDEF_FFI_MANGO_CORE_RUST_FUTURE_FREE_I64
void ffi_mango_core_rust_future_free_i64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_MANGO_CORE_RUST_FUTURE_COMPLETE_I64
#define UNIFFI_FFIDEF_FFI_MANGO_CORE_RUST_FUTURE_COMPLETE_I64
int64_t ffi_mango_core_rust_future_complete_i64(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_MANGO_CORE_RUST_FUTURE_POLL_F32
#define UNIFFI_FFIDEF_FFI_MANGO_CORE_RUST_FUTURE_POLL_F32
void ffi_mango_core_rust_future_poll_f32(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_MANGO_CORE_RUST_FUTURE_CANCEL_F32
#define UNIFFI_FFIDEF_FFI_MANGO_CORE_RUST_FUTURE_CANCEL_F32
void ffi_mango_core_rust_future_cancel_f32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_MANGO_CORE_RUST_FUTURE_FREE_F32
#define UNIFFI_FFIDEF_FFI_MANGO_CORE_RUST_FUTURE_FREE_F32
void ffi_mango_core_rust_future_free_f32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_MANGO_CORE_RUST_FUTURE_COMPLETE_F32
#define UNIFFI_FFIDEF_FFI_MANGO_CORE_RUST_FUTURE_COMPLETE_F32
float ffi_mango_core_rust_future_complete_f32(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_MANGO_CORE_RUST_FUTURE_POLL_F64
#define UNIFFI_FFIDEF_FFI_MANGO_CORE_RUST_FUTURE_POLL_F64
void ffi_mango_core_rust_future_poll_f64(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_MANGO_CORE_RUST_FUTURE_CANCEL_F64
#define UNIFFI_FFIDEF_FFI_MANGO_CORE_RUST_FUTURE_CANCEL_F64
void ffi_mango_core_rust_future_cancel_f64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_MANGO_CORE_RUST_FUTURE_FREE_F64
#define UNIFFI_FFIDEF_FFI_MANGO_CORE_RUST_FUTURE_FREE_F64
void ffi_mango_core_rust_future_free_f64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_MANGO_CORE_RUST_FUTURE_COMPLETE_F64
#define UNIFFI_FFIDEF_FFI_MANGO_CORE_RUST_FUTURE_COMPLETE_F64
double ffi_mango_core_rust_future_complete_f64(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_MANGO_CORE_RUST_FUTURE_POLL_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_MANGO_CORE_RUST_FUTURE_POLL_RUST_BUFFER
void ffi_mango_core_rust_future_poll_rust_buffer(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_MANGO_CORE_RUST_FUTURE_CANCEL_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_MANGO_CORE_RUST_FUTURE_CANCEL_RUST_BUFFER
void ffi_mango_core_rust_future_cancel_rust_buffer(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_MANGO_CORE_RUST_FUTURE_FREE_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_MANGO_CORE_RUST_FUTURE_FREE_RUST_BUFFER
void ffi_mango_core_rust_future_free_rust_buffer(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_MANGO_CORE_RUST_FUTURE_COMPLETE_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_MANGO_CORE_RUST_FUTURE_COMPLETE_RUST_BUFFER
RustBuffer ffi_mango_core_rust_future_complete_rust_buffer(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_MANGO_CORE_RUST_FUTURE_POLL_VOID
#define UNIFFI_FFIDEF_FFI_MANGO_CORE_RUST_FUTURE_POLL_VOID
void ffi_mango_core_rust_future_poll_void(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_MANGO_CORE_RUST_FUTURE_CANCEL_VOID
#define UNIFFI_FFIDEF_FFI_MANGO_CORE_RUST_FUTURE_CANCEL_VOID
void ffi_mango_core_rust_future_cancel_void(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_MANGO_CORE_RUST_FUTURE_FREE_VOID
#define UNIFFI_FFIDEF_FFI_MANGO_CORE_RUST_FUTURE_FREE_VOID
void ffi_mango_core_rust_future_free_void(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_MANGO_CORE_RUST_FUTURE_COMPLETE_VOID
#define UNIFFI_FFIDEF_FFI_MANGO_CORE_RUST_FUTURE_COMPLETE_VOID
void ffi_mango_core_rust_future_complete_void(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_MANGO_CORE_CHECKSUM_FUNC_KNOWN_PROVIDER_PRESETS
#define UNIFFI_FFIDEF_UNIFFI_MANGO_CORE_CHECKSUM_FUNC_KNOWN_PROVIDER_PRESETS
uint16_t uniffi_mango_core_checksum_func_known_provider_presets(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_MANGO_CORE_CHECKSUM_FUNC_MODEL_SUPPORTS_VISION
#define UNIFFI_FFIDEF_UNIFFI_MANGO_CORE_CHECKSUM_FUNC_MODEL_SUPPORTS_VISION
uint16_t uniffi_mango_core_checksum_func_model_supports_vision(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_MANGO_CORE_CHECKSUM_FUNC_LOCAL_MODEL_CATALOG
#define UNIFFI_FFIDEF_UNIFFI_MANGO_CORE_CHECKSUM_FUNC_LOCAL_MODEL_CATALOG
uint16_t uniffi_mango_core_checksum_func_local_model_catalog(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_MANGO_CORE_CHECKSUM_METHOD_FFIAPP_DISPATCH
#define UNIFFI_FFIDEF_UNIFFI_MANGO_CORE_CHECKSUM_METHOD_FFIAPP_DISPATCH
uint16_t uniffi_mango_core_checksum_method_ffiapp_dispatch(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_MANGO_CORE_CHECKSUM_METHOD_FFIAPP_EXPORT_CONVERSATION_MARKDOWN
#define UNIFFI_FFIDEF_UNIFFI_MANGO_CORE_CHECKSUM_METHOD_FFIAPP_EXPORT_CONVERSATION_MARKDOWN
uint16_t uniffi_mango_core_checksum_method_ffiapp_export_conversation_markdown(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_MANGO_CORE_CHECKSUM_METHOD_FFIAPP_GET_DIRECTORY_BOOKMARK
#define UNIFFI_FFIDEF_UNIFFI_MANGO_CORE_CHECKSUM_METHOD_FFIAPP_GET_DIRECTORY_BOOKMARK
uint16_t uniffi_mango_core_checksum_method_ffiapp_get_directory_bookmark(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_MANGO_CORE_CHECKSUM_METHOD_FFIAPP_GET_RAW_ATTESTATION_REPORT
#define UNIFFI_FFIDEF_UNIFFI_MANGO_CORE_CHECKSUM_METHOD_FFIAPP_GET_RAW_ATTESTATION_REPORT
uint16_t uniffi_mango_core_checksum_method_ffiapp_get_raw_attestation_report(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_MANGO_CORE_CHECKSUM_METHOD_FFIAPP_LIST_DIRECTORY_FINGERPRINTS
#define UNIFFI_FFIDEF_UNIFFI_MANGO_CORE_CHECKSUM_METHOD_FFIAPP_LIST_DIRECTORY_FINGERPRINTS
uint16_t uniffi_mango_core_checksum_method_ffiapp_list_directory_fingerprints(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_MANGO_CORE_CHECKSUM_METHOD_FFIAPP_LISTEN_FOR_UPDATES
#define UNIFFI_FFIDEF_UNIFFI_MANGO_CORE_CHECKSUM_METHOD_FFIAPP_LISTEN_FOR_UPDATES
uint16_t uniffi_mango_core_checksum_method_ffiapp_listen_for_updates(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_MANGO_CORE_CHECKSUM_METHOD_FFIAPP_READ_ENCRYPTED_IMAGE
#define UNIFFI_FFIDEF_UNIFFI_MANGO_CORE_CHECKSUM_METHOD_FFIAPP_READ_ENCRYPTED_IMAGE
uint16_t uniffi_mango_core_checksum_method_ffiapp_read_encrypted_image(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_MANGO_CORE_CHECKSUM_METHOD_FFIAPP_STATE
#define UNIFFI_FFIDEF_UNIFFI_MANGO_CORE_CHECKSUM_METHOD_FFIAPP_STATE
uint16_t uniffi_mango_core_checksum_method_ffiapp_state(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_MANGO_CORE_CHECKSUM_METHOD_FFIAPP_SYNC
#define UNIFFI_FFIDEF_UNIFFI_MANGO_CORE_CHECKSUM_METHOD_FFIAPP_SYNC
uint16_t uniffi_mango_core_checksum_method_ffiapp_sync(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_MANGO_CORE_CHECKSUM_METHOD_LOCALGENERATIONCONTEXT_EMIT_ERROR
#define UNIFFI_FFIDEF_UNIFFI_MANGO_CORE_CHECKSUM_METHOD_LOCALGENERATIONCONTEXT_EMIT_ERROR
uint16_t uniffi_mango_core_checksum_method_localgenerationcontext_emit_error(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_MANGO_CORE_CHECKSUM_METHOD_LOCALGENERATIONCONTEXT_EMIT_TOKEN
#define UNIFFI_FFIDEF_UNIFFI_MANGO_CORE_CHECKSUM_METHOD_LOCALGENERATIONCONTEXT_EMIT_TOKEN
uint16_t uniffi_mango_core_checksum_method_localgenerationcontext_emit_token(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_MANGO_CORE_CHECKSUM_METHOD_LOCALGENERATIONCONTEXT_IS_CANCELLED
#define UNIFFI_FFIDEF_UNIFFI_MANGO_CORE_CHECKSUM_METHOD_LOCALGENERATIONCONTEXT_IS_CANCELLED
uint16_t uniffi_mango_core_checksum_method_localgenerationcontext_is_cancelled(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_MANGO_CORE_CHECKSUM_METHOD_LOCALMODELDOWNLOADCONTEXT_EMIT_PROGRESS
#define UNIFFI_FFIDEF_UNIFFI_MANGO_CORE_CHECKSUM_METHOD_LOCALMODELDOWNLOADCONTEXT_EMIT_PROGRESS
uint16_t uniffi_mango_core_checksum_method_localmodeldownloadcontext_emit_progress(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_MANGO_CORE_CHECKSUM_CONSTRUCTOR_FFIAPP_NEW
#define UNIFFI_FFIDEF_UNIFFI_MANGO_CORE_CHECKSUM_CONSTRUCTOR_FFIAPP_NEW
uint16_t uniffi_mango_core_checksum_constructor_ffiapp_new(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_MANGO_CORE_CHECKSUM_METHOD_APPRECONCILER_RECONCILE
#define UNIFFI_FFIDEF_UNIFFI_MANGO_CORE_CHECKSUM_METHOD_APPRECONCILER_RECONCILE
uint16_t uniffi_mango_core_checksum_method_appreconciler_reconcile(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_MANGO_CORE_CHECKSUM_METHOD_BIOMETRICPROVIDER_BIOMETRIC_STATUS
#define UNIFFI_FFIDEF_UNIFFI_MANGO_CORE_CHECKSUM_METHOD_BIOMETRICPROVIDER_BIOMETRIC_STATUS
uint16_t uniffi_mango_core_checksum_method_biometricprovider_biometric_status(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_MANGO_CORE_CHECKSUM_METHOD_BIOMETRICPROVIDER_AUTHENTICATE
#define UNIFFI_FFIDEF_UNIFFI_MANGO_CORE_CHECKSUM_METHOD_BIOMETRICPROVIDER_AUTHENTICATE
uint16_t uniffi_mango_core_checksum_method_biometricprovider_authenticate(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_MANGO_CORE_CHECKSUM_METHOD_FILEPICKERPROVIDER_PICK_FILE
#define UNIFFI_FFIDEF_UNIFFI_MANGO_CORE_CHECKSUM_METHOD_FILEPICKERPROVIDER_PICK_FILE
uint16_t uniffi_mango_core_checksum_method_filepickerprovider_pick_file(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_MANGO_CORE_CHECKSUM_METHOD_KEYCHAINPROVIDER_STORE
#define UNIFFI_FFIDEF_UNIFFI_MANGO_CORE_CHECKSUM_METHOD_KEYCHAINPROVIDER_STORE
uint16_t uniffi_mango_core_checksum_method_keychainprovider_store(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_MANGO_CORE_CHECKSUM_METHOD_KEYCHAINPROVIDER_LOAD
#define UNIFFI_FFIDEF_UNIFFI_MANGO_CORE_CHECKSUM_METHOD_KEYCHAINPROVIDER_LOAD
uint16_t uniffi_mango_core_checksum_method_keychainprovider_load(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_MANGO_CORE_CHECKSUM_METHOD_KEYCHAINPROVIDER_DELETE
#define UNIFFI_FFIDEF_UNIFFI_MANGO_CORE_CHECKSUM_METHOD_KEYCHAINPROVIDER_DELETE
uint16_t uniffi_mango_core_checksum_method_keychainprovider_delete(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_MANGO_CORE_CHECKSUM_METHOD_EMBEDDINGPROVIDER_EMBED
#define UNIFFI_FFIDEF_UNIFFI_MANGO_CORE_CHECKSUM_METHOD_EMBEDDINGPROVIDER_EMBED
uint16_t uniffi_mango_core_checksum_method_embeddingprovider_embed(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_MANGO_CORE_CHECKSUM_METHOD_LOCALLLMPROVIDER_LOAD_MODEL
#define UNIFFI_FFIDEF_UNIFFI_MANGO_CORE_CHECKSUM_METHOD_LOCALLLMPROVIDER_LOAD_MODEL
uint16_t uniffi_mango_core_checksum_method_localllmprovider_load_model(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_MANGO_CORE_CHECKSUM_METHOD_LOCALLLMPROVIDER_DOWNLOAD_MODEL_FILE
#define UNIFFI_FFIDEF_UNIFFI_MANGO_CORE_CHECKSUM_METHOD_LOCALLLMPROVIDER_DOWNLOAD_MODEL_FILE
uint16_t uniffi_mango_core_checksum_method_localllmprovider_download_model_file(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_MANGO_CORE_CHECKSUM_METHOD_LOCALLLMPROVIDER_PLATFORM_HTTP_REQUEST
#define UNIFFI_FFIDEF_UNIFFI_MANGO_CORE_CHECKSUM_METHOD_LOCALLLMPROVIDER_PLATFORM_HTTP_REQUEST
uint16_t uniffi_mango_core_checksum_method_localllmprovider_platform_http_request(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_MANGO_CORE_CHECKSUM_METHOD_LOCALLLMPROVIDER_GENERATE
#define UNIFFI_FFIDEF_UNIFFI_MANGO_CORE_CHECKSUM_METHOD_LOCALLLMPROVIDER_GENERATE
uint16_t uniffi_mango_core_checksum_method_localllmprovider_generate(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_MANGO_CORE_CHECKSUM_METHOD_LOCALLLMPROVIDER_UNLOAD
#define UNIFFI_FFIDEF_UNIFFI_MANGO_CORE_CHECKSUM_METHOD_LOCALLLMPROVIDER_UNLOAD
uint16_t uniffi_mango_core_checksum_method_localllmprovider_unload(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_MANGO_CORE_CHECKSUM_METHOD_LOCALLLMPROVIDER_LOADED_MODEL_PATH
#define UNIFFI_FFIDEF_UNIFFI_MANGO_CORE_CHECKSUM_METHOD_LOCALLLMPROVIDER_LOADED_MODEL_PATH
uint16_t uniffi_mango_core_checksum_method_localllmprovider_loaded_model_path(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_MANGO_CORE_CHECKSUM_METHOD_LOCALLLMPROVIDER_DEVICE_CAPABILITY
#define UNIFFI_FFIDEF_UNIFFI_MANGO_CORE_CHECKSUM_METHOD_LOCALLLMPROVIDER_DEVICE_CAPABILITY
uint16_t uniffi_mango_core_checksum_method_localllmprovider_device_capability(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_MANGO_CORE_UNIFFI_CONTRACT_VERSION
#define UNIFFI_FFIDEF_FFI_MANGO_CORE_UNIFFI_CONTRACT_VERSION
uint32_t ffi_mango_core_uniffi_contract_version(void
    
);
#endif

